// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Telemetry.Infrastructure.Persistence;

#nullable disable

namespace Telemetry.Infrastructure.Migrations
{
    [DbContext(typeof(TelemetryDbContext))]
    [Migration("20260709194653_AddValueObjects")]
    partial class AddValueObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Telemetry.Domain.Entities.AggregateTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAggregated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_aggregated");

                    b.Property<int>("Period")
                        .HasColumnType("integer")
                        .HasColumnName("period");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.ComplexProperty<Dictionary<string, object>>("Summary", "Telemetry.Domain.Entities.AggregateTelemetry.Summary#TelemetrySummary", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("AvgValue")
                                .HasPrecision(10, 4)
                                .HasColumnType("double precision")
                                .HasColumnName("summary_avg_value");

                            b1.Property<int>("Count")
                                .HasColumnType("integer")
                                .HasColumnName("summary_count");

                            b1.Property<double>("MaxValue")
                                .HasPrecision(10, 4)
                                .HasColumnType("double precision")
                                .HasColumnName("summary_max_value");

                            b1.Property<double>("MinValue")
                                .HasPrecision(10, 4)
                                .HasColumnType("double precision")
                                .HasColumnName("summary_min_value");
                        });

                    b.HasKey("Id")
                        .HasName("pk_telemetry_aggregate_data");

                    b.HasIndex("IsAggregated")
                        .HasDatabaseName("ix_telemetry_aggregate_data_is_aggregated");

                    b.HasIndex("SensorId", "Period", "PeriodStart")
                        .HasDatabaseName("ix_telemetry_aggregate_data_sensor_id_period_period_start");

                    b.ToTable("telemetry_aggregate_data", (string)null);
                });

            modelBuilder.Entity("Telemetry.Domain.Entities.Ecosystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_ecosystems");

                    b.HasIndex("ControllerId")
                        .HasDatabaseName("ix_ecosystems_controller_id");

                    b.ToTable("ecosystems", (string)null);
                });

            modelBuilder.Entity("Telemetry.Domain.Entities.RawTelemetry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_message_id");

                    b.Property<bool>("IsAggregated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_aggregated");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<double>("Value")
                        .HasPrecision(10, 4)
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_telemetry_raw_data");

                    b.HasIndex("ExternalMessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_telemetry_raw_data_external_message_id");

                    b.HasIndex("IsAggregated")
                        .HasDatabaseName("ix_telemetry_raw_data_is_aggregated");

                    b.HasIndex("SensorId", "RecordedAt")
                        .HasDatabaseName("ix_telemetry_raw_data_sensor_id_recorded_at");

                    b.ToTable("telemetry_raw_data", (string)null);
                });

            modelBuilder.Entity("Telemetry.Domain.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EcosystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("ecosystem_id");

                    b.Property<bool>("IsDataDelayed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_data_delayed");

                    b.Property<double>("LastValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("double precision")
                        .HasColumnName("last_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("unit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("EcosystemId")
                        .HasDatabaseName("ix_sensors_ecosystem_id");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("Telemetry.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredOnUtc")
                        .HasDatabaseName("ix_outbox_messages_occurred_on_utc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Telemetry.Domain.Entities.AggregateTelemetry", b =>
                {
                    b.HasOne("Telemetry.Domain.Entities.Sensor", null)
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telemetry_aggregate_data_sensors_sensor_id");
                });

            modelBuilder.Entity("Telemetry.Domain.Entities.RawTelemetry", b =>
                {
                    b.HasOne("Telemetry.Domain.Entities.Sensor", null)
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telemetry_raw_data_sensors_sensor_id");
                });
#pragma warning restore 612, 618
        }
    }
}
