<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="DotNetEnv" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Elasticsearch" />
        <PackageReference Include="Serilog.Exceptions" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BuildingBlocks.Domain\BuildingBlocks.Domain.csproj" />
    </ItemGroup>

</Project>
