// <auto-generated />
using System;
using Device.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Device.Infrastructure.Migrations
{
    [DbContext(typeof(DeviceDbContext))]
    [Migration("20260423125448_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Device.Domain.Entities.ControllerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceTokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_token_hash");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_controllers");

                    b.HasIndex("DeviceTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_controllers_device_token_hash");

                    b.HasIndex("MacAddress")
                        .IsUnique()
                        .HasDatabaseName("ix_controllers_mac_address");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_controllers_user_id");

                    b.ToTable("controllers", (string)null);
                });

            modelBuilder.Entity("Device.Domain.Entities.RelayEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HardwarePin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hardware_pin");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.HasKey("Id")
                        .HasName("pk_relays");

                    b.HasIndex("ControllerId", "HardwarePin")
                        .IsUnique()
                        .HasDatabaseName("ix_relays_controller_id_hardware_pin");

                    b.ToTable("relays", (string)null);
                });

            modelBuilder.Entity("Device.Domain.Entities.SensorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HardwarePin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("hardware_pin");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("ControllerId", "HardwarePin")
                        .IsUnique()
                        .HasDatabaseName("ix_sensors_controller_id_hardware_pin");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("Device.Domain.Entities.RelayEntity", b =>
                {
                    b.HasOne("Device.Domain.Entities.ControllerEntity", null)
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relays_controllers_controller_id");
                });

            modelBuilder.Entity("Device.Domain.Entities.SensorEntity", b =>
                {
                    b.HasOne("Device.Domain.Entities.ControllerEntity", null)
                        .WithMany()
                        .HasForeignKey("ControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_controllers_controller_id");
                });
#pragma warning restore 612, 618
        }
    }
}
