version: '3.8'

services:
  telemetry-db:
    image: postgres:18
    container_name: telemetry-db
    environment:
      - POSTGRES_DB=telemetry_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust 
    ports:
      - "5438:5432"
    volumes:
      - telemetry-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telemetry_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - aqua-network

  device-db:
    image: postgres:18
    container_name: device-db
    environment:
      - POSTGRES_DB=device_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust  
    ports:
      - "5439:5432"
    volumes:
      - device-db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d device_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - aqua-network

  control-db:
      image: postgres:18
      container_name: control-db
      environment:
        - POSTGRES_DB=control_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_HOST_AUTH_METHOD=trust 
      ports:
        - "5440:5432"
      volumes:
        - control-db-data:/var/lib/postgresql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d control_db"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
        - aqua-network

  identity-db:
      image: postgres:18
      container_name: identity-db
      environment:
        - POSTGRES_DB=identity_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_HOST_AUTH_METHOD=trust 
      ports:
        - "5441:5432"
      volumes:
        - identity-db-data:/var/lib/postgresql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d identity_db"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
        - aqua-network

  notification-db:
      image: postgres:18
      container_name: notification-db
      environment:
        - POSTGRES_DB=notification_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_HOST_AUTH_METHOD=trust
      ports:
        - "5442:5432"
      volumes:
        - notification-db-data:/var/lib/postgresql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d notification_db"]
        interval: 5s
        timeout: 5s
        retries: 5
      networks:
        - aqua-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" 
    ports:
      - "9200:9200"
    networks:
      - aqua-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - aqua-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aqua-network
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    build:
      context: .
      dockerfile: src\Gateway\ApiGateway\Dockerfile
    ports:
      - "5055:8080"
    depends_on:
      telemetry-api:
        condition: service_healthy
      device-api:
        condition: service_healthy
      control-api:
        condition: service_healthy
      identity-api:
        condition: service_healthy
      notification-api:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - JwtOptions__SecretKey=super-secret-key-must-be-at-least-32-characters-long
      - JwtOptions__Issuer=AquaSmart.Identity
      - JwtOptions__Audience=AquaSmart.Gateway
      - JwtOptions__ExpiresHours=12
    networks:
      - aqua-network

  telemetry-api:
    container_name: telemetry-api
    image: telemetry-api
    build:
      context: . 
      dockerfile: src/Services/TelemetryService/TelemetryService/Dockerfile
    depends_on:
      telemetry-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080  
      - ConnectionStrings__SystemDbContext=Host=telemetry-db;Database=telemetry_db;Username=postgres;Password=password
      - ElasticConfiguration__Uri=http://elasticsearch:9200
      - RabbitMqOptions__Host=amqp://rabbitmq:5672
      - RabbitMqOptions__UserName=guest
      - RabbitMqOptions__Password=guest
      - JwtOptions__SecretKey=super-secret-key-must-be-at-least-32-characters-long
      - JwtOptions__Issuer=AquaSmart.Identity
      - JwtOptions__Audience=AquaSmart.Gateway
      - JwtOptions__ExpiresHours=12
      - MT_LICENSE=community  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - aqua-network

  device-api:
    container_name: device-api
    image: device-api 
    build:
      context: . 
      dockerfile: src/Services/DeviceService/DeviceService/Dockerfile
    ports:
      - "5237:8080"
    depends_on:
      device-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DeviceDbContext=Host=device-db;Database=device_db;Username=postgres;Password=password
      - ElasticConfiguration__Uri=http://elasticsearch:9200
      - RabbitMqOptions__Host=amqp://rabbitmq:5672
      - RabbitMqOptions__UserName=guest
      - RabbitMqOptions__Password=guest
      - JwtOptions__SecretKey=super-secret-key-must-be-at-least-32-characters-long
      - JwtOptions__Issuer=AquaSmart.Identity
      - JwtOptions__Audience=AquaSmart.Gateway
      - JwtOptions__ExpiresHours=12
      - MT_LICENSE=community  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - aqua-network

  control-api:
    container_name: control-api
    image: control-api
    build:
      context: . 
      dockerfile: src/Services/ControlService/ControlService/Dockerfile
    depends_on:
      control-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__ControlDbContext=Host=control-db;Database=control_db;Username=postgres;Password=password
      - RabbitMqOptions__Host=amqp://rabbitmq:5672
      - RabbitMqOptions__UserName=guest
      - RabbitMqOptions__Password=guest
      - JwtOptions__SecretKey=super-secret-key-must-be-at-least-32-characters-long
      - JwtOptions__Issuer=AquaSmart.Identity
      - JwtOptions__Audience=AquaSmart.Gateway
      - JwtOptions__ExpiresHours=12
      - MT_LICENSE=community
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - aqua-network

  identity-api:
    container_name: identity-api
    image: identity-api
    build:
      context: .
      dockerfile: src/Services/IdentityService/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__IdentityDbContext=Host=identity-db;Database=identity_db;Username=postgres;Password=password
      - JwtOptions__SecretKey=super-secret-key-must-be-at-least-32-characters-long
      - JwtOptions__Issuer=AquaSmart.Identity
      - JwtOptions__Audience=AquaSmart.Gateway
      - JwtOptions__ExpiresHours=12
      - RabbitMqOptions__Host=amqp://rabbitmq:5672
      - RabbitMqOptions__UserName=guest
      - RabbitMqOptions__Password=guest
    depends_on:
      identity-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - aqua-network

  notification-api:
    container_name: notification-api
    build:
      context: .
      dockerfile: src\Services\NotificationService\NotificationService\Dockerfile
    depends_on:
      notification-db: 
        condition: service_healthy 
      rabbitmq: 
        condition: service_healthy 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 
      - ConnectionStrings__NotificationDbContext=Host=notification-db;Database=notification_db;Username=postgres;Password=password
      - RabbitMqOptions__Host=amqp://rabbitmq:5672
      - RabbitMqOptions__UserName=guest
      - RabbitMqOptions__Password=guest
      - JwtOptions__SecretKey=super-secret-key-must-be-at-least-32-characters-long
      - JwtOptions__Issuer=AquaSmart.Identity
      - JwtOptions__Audience=AquaSmart.Gateway
      - JwtOptions__ExpiresHours=12
      - TelegramOptions__BotToken=test
      - EmailOptions__Host=test
      - EmailOptions__UserName=test
      - EmailOptions__Password=test
      - MT_LICENSE=community
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - aqua-network

networks:
  aqua-network:
    driver: bridge

volumes:
  telemetry-db-data:
  device-db-data:
  control-db-data:
  identity-db-data:
  notification-db-data:
