<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" />
        <PackageReference Include="Serilog.AspNetCore" />
        <PackageReference Include="Serilog.Sinks.Elasticsearch" />
        <PackageReference Include="Serilog.Exceptions" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.GrpcContracts\BuildingBlocks.GrpcContracts.csproj" />
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Presentation\BuildingBlocks.Presentation.csproj" />
        <ProjectReference Include="..\Device.Application\Device.Application.csproj" />
        <ProjectReference Include="..\Device.Infrastrucrute\Device.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Device.Application.UnitTests" />
    </ItemGroup>

</Project>
