<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Infrastructure\BuildingBlocks.Infrastructure.csproj" />
      <ProjectReference Include="..\TelegramBot.Domain\TelegramBot.Domain.csproj" />
      <ProjectReference Include="..\TelegramBotService,Application\TelegramBotService,Application.csproj" />
      <ProjectReference Include="..\TelegramBotService.Infrastructure\TelegramBotService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
