global using AutoMapper;
global using Contracts.Constants;
global using Contracts.Enums;
global using Contracts.Results;
global using Device.Domain.Entities;
global using Device.Domain.Entities.Sensors;
global using Device.Domain.Interfaces;
global using FluentValidation;
global using MediatR;
