// <auto-generated />
using System;
using Control.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Control.Infrastructure.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    [Migration("20260422211658_UpdateUserAndAquariumOwnership")]
    partial class UpdateUserAndAquariumOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Control.Domain.Entities.AquariumEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_aquariums");

                    b.HasIndex("ControllerId")
                        .IsUnique()
                        .HasDatabaseName("ix_aquariums_controller_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_aquariums_user_id");

                    b.ToTable("aquariums", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.AutomationRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<Guid>("AquariumId")
                        .HasColumnType("uuid")
                        .HasColumnName("aquarium_id");

                    b.Property<int>("Condition")
                        .HasColumnType("integer")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Hysteresis")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("hysteresis");

                    b.Property<Guid>("RelayId")
                        .HasColumnType("uuid")
                        .HasColumnName("relay_id");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<double>("Threshold")
                        .HasPrecision(18, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.HasKey("Id")
                        .HasName("pk_automation_rules");

                    b.HasIndex("AquariumId")
                        .HasDatabaseName("ix_automation_rules_aquarium_id");

                    b.HasIndex("RelayId")
                        .HasDatabaseName("ix_automation_rules_relay_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_automation_rules_sensor_id");

                    b.ToTable("automation_rules", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.RelayEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AquariumId")
                        .HasColumnType("uuid")
                        .HasColumnName("aquarium_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.HasKey("Id")
                        .HasName("pk_relays");

                    b.HasIndex("AquariumId")
                        .HasDatabaseName("ix_relays_aquarium_id");

                    b.ToTable("relays", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.ScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AquariumId")
                        .HasColumnType("uuid")
                        .HasColumnName("aquarium_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cron_expression");

                    b.Property<double>("DurationMin")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_min");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enable");

                    b.Property<bool>("IsFadeMode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fade_mode");

                    b.Property<Guid>("RelayId")
                        .HasColumnType("uuid")
                        .HasColumnName("relay_id");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.HasIndex("AquariumId")
                        .HasDatabaseName("ix_schedules_aquarium_id");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.SensorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AquariumId")
                        .HasColumnType("uuid")
                        .HasColumnName("aquarium_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("AquariumId")
                        .HasDatabaseName("ix_sensors_aquarium_id");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.VacationModeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AquariumId")
                        .HasColumnType("uuid")
                        .HasColumnName("aquarium_id");

                    b.Property<double>("CalculatedFeed")
                        .HasColumnType("double precision")
                        .HasColumnName("calculated_feed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_vacations");

                    b.HasIndex("AquariumId")
                        .HasDatabaseName("ix_vacations_aquarium_id");

                    b.ToTable("vacations", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.AutomationRuleEntity", b =>
                {
                    b.HasOne("Control.Domain.Entities.AquariumEntity", null)
                        .WithMany()
                        .HasForeignKey("AquariumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_automation_rules_aquariums_aquarium_id");
                });

            modelBuilder.Entity("Control.Domain.Entities.RelayEntity", b =>
                {
                    b.HasOne("Control.Domain.Entities.AquariumEntity", null)
                        .WithMany()
                        .HasForeignKey("AquariumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relays_aquariums_aquarium_id");
                });

            modelBuilder.Entity("Control.Domain.Entities.ScheduleEntity", b =>
                {
                    b.HasOne("Control.Domain.Entities.AquariumEntity", null)
                        .WithMany()
                        .HasForeignKey("AquariumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedules_aquariums_aquarium_id");
                });

            modelBuilder.Entity("Control.Domain.Entities.SensorEntity", b =>
                {
                    b.HasOne("Control.Domain.Entities.AquariumEntity", null)
                        .WithMany()
                        .HasForeignKey("AquariumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_aquariums_aquarium_id");
                });

            modelBuilder.Entity("Control.Domain.Entities.VacationModeEntity", b =>
                {
                    b.HasOne("Control.Domain.Entities.AquariumEntity", null)
                        .WithMany()
                        .HasForeignKey("AquariumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vacations_aquariums_aquarium_id");
                });
#pragma warning restore 612, 618
        }
    }
}
