// <auto-generated />
using System;
using Control.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Control.Infrastructure.Migrations
{
    [DbContext(typeof(SystemDbContext))]
    partial class SystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Control.Domain.Entities.AutomationRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EcosystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("ecosystem_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Operator")
                        .HasColumnType("integer")
                        .HasColumnName("operator");

                    b.Property<Guid>("RelayId")
                        .HasColumnType("uuid")
                        .HasColumnName("relay_id");

                    b.HasKey("Id")
                        .HasName("pk_automation_rules");

                    b.HasIndex("EcosystemId")
                        .HasDatabaseName("ix_automation_rules_ecosystem_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_automation_rules_is_active");

                    b.ToTable("automation_rules", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.EcosystemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_ecosystems");

                    b.HasIndex("ControllerId")
                        .IsUnique()
                        .HasDatabaseName("ix_ecosystems_controller_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_ecosystems_user_id");

                    b.ToTable("ecosystems", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.RelayEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EcosystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("ecosystem_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsManual")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manual");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid?>("PowerSensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("power_sensor_id");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer")
                        .HasColumnName("purpose");

                    b.HasKey("Id")
                        .HasName("pk_relays");

                    b.HasIndex("EcosystemId")
                        .HasDatabaseName("ix_relays_ecosystem_id");

                    b.HasIndex("PowerSensorId")
                        .HasDatabaseName("ix_relays_power_sensor_id")
                        .HasFilter("power_sensor_id IS NOT NULL");

                    b.ToTable("relays", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.RuleConditionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AutomationRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("automation_rule_id");

                    b.Property<int>("Condition")
                        .HasColumnType("integer")
                        .HasColumnName("condition");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Hysteresis")
                        .HasPrecision(10, 4)
                        .HasColumnType("double precision")
                        .HasColumnName("hysteresis");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<double>("Threshold")
                        .HasPrecision(10, 4)
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.HasKey("Id")
                        .HasName("pk_rule_conditions");

                    b.HasIndex("AutomationRuleId")
                        .HasDatabaseName("ix_rule_conditions_automation_rule_id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("ix_rule_conditions_sensor_id");

                    b.ToTable("rule_conditions", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.ScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("cron_expression");

                    b.Property<double>("DurationMin")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_min");

                    b.Property<Guid>("EcosystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("ecosystem_id");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enable");

                    b.Property<bool>("IsFadeMode")
                        .HasColumnType("boolean")
                        .HasColumnName("is_fade_mode");

                    b.Property<Guid>("RelayId")
                        .HasColumnType("uuid")
                        .HasColumnName("relay_id");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.HasIndex("EcosystemId")
                        .HasDatabaseName("ix_schedules_ecosystem_id");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.SensorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ControllerId")
                        .HasColumnType("uuid")
                        .HasColumnName("controller_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EcosystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("ecosystem_id");

                    b.Property<double>("LastValue")
                        .HasPrecision(10, 4)
                        .HasColumnType("double precision")
                        .HasColumnName("last_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_sensors");

                    b.HasIndex("EcosystemId")
                        .HasDatabaseName("ix_sensors_ecosystem_id");

                    b.ToTable("sensors", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.VacationModeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("CalculatedFeed")
                        .HasColumnType("double precision")
                        .HasColumnName("calculated_feed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EcosystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("ecosystem_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_vacations");

                    b.HasIndex("EcosystemId")
                        .HasDatabaseName("ix_vacations_ecosystem_id");

                    b.ToTable("vacations", (string)null);
                });

            modelBuilder.Entity("Control.Domain.Entities.AutomationRuleEntity", b =>
                {
                    b.HasOne("Control.Domain.Entities.EcosystemEntity", null)
                        .WithMany()
                        .HasForeignKey("EcosystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_automation_rules_ecosystems_ecosystem_id");
                });

            modelBuilder.Entity("Control.Domain.Entities.RelayEntity", b =>
                {
                    b.HasOne("Control.Domain.Entities.EcosystemEntity", null)
                        .WithMany()
                        .HasForeignKey("EcosystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relays_ecosystems_ecosystem_id");
                });

            modelBuilder.Entity("Control.Domain.Entities.RuleConditionEntity", b =>
                {
                    b.HasOne("Control.Domain.Entities.AutomationRuleEntity", null)
                        .WithMany("Conditions")
                        .HasForeignKey("AutomationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rule_conditions_automation_rules_automation_rule_id");
                });

            modelBuilder.Entity("Control.Domain.Entities.ScheduleEntity", b =>
                {
                    b.HasOne("Control.Domain.Entities.EcosystemEntity", null)
                        .WithMany()
                        .HasForeignKey("EcosystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_schedules_ecosystems_ecosystem_id");
                });

            modelBuilder.Entity("Control.Domain.Entities.SensorEntity", b =>
                {
                    b.HasOne("Control.Domain.Entities.EcosystemEntity", null)
                        .WithMany()
                        .HasForeignKey("EcosystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sensors_ecosystems_ecosystem_id");
                });

            modelBuilder.Entity("Control.Domain.Entities.VacationModeEntity", b =>
                {
                    b.HasOne("Control.Domain.Entities.EcosystemEntity", null)
                        .WithMany()
                        .HasForeignKey("EcosystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vacations_ecosystems_ecosystem_id");
                });

            modelBuilder.Entity("Control.Domain.Entities.AutomationRuleEntity", b =>
                {
                    b.Navigation("Conditions");
                });
#pragma warning restore 612, 618
        }
    }
}
