<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Dapper" />
        <PackageReference Include="BCrypt.Net-Next" />
        <PackageReference Include="MassTransit" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.Extensions.Identity.Core" />
        <PackageReference Include="Microsoft.Extensions.Identity.Stores" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Application\BuildingBlocks.Application.csproj" />
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.IntegrationEvents\BuildingBlocks.IntegrationEvents.csproj" />
        <ProjectReference Include="..\..\..\BuildingBlocks\BuildingBlocks.Presentation\BuildingBlocks.Presentation.csproj" />
        <ProjectReference Include="..\IdentityService.Domain\IdentityService.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Identity.Application.UnitTests" />
    </ItemGroup>
</Project>
